# Generated by Django 5.0.6 on 2024-10-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_task_typex'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.user'),
        ),
    ]
