# Generated by Django 5.0.6 on 2024-10-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_user_remove_task_email_alter_task_assignee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
